name: CI - Testing | Action
on:
  push:

jobs:
  cache:
    name: Create Cache If Needed
    runs-on: ubuntu-latest
    steps:
      - name: Step -> Checkout code
        uses: actions/checkout@v3

      - name: Step -> Generate cache
        id: cache-id
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache
          key: strangler-cache-${{ github.ref_name }}-v1

      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache

      - name: Step -> Use cache
        run: |
          whereis wkhtmltopdf || true

  bundler-audit:
    name: Bundler Audit
    needs: cache
    runs-on: ubuntu-latest

    steps:
      - name: Step -> Checkout code
        uses: actions/checkout@v3

      - name: Step -> Generate cache
        id: cache-id
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache
          key: strangler-cache-${{ github.ref_name }}-v1

      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache

      - name: Step -> Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Step -> Bundler Audit
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit

  rubocop:
    name: Rubocop Test
    needs: [cache, bundler-audit]
    runs-on: ubuntu-latest

    steps:
      - name: Step -> Checkout code
        uses: actions/checkout@v3

      - name: Step -> Generate cache
        id: cache-id
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache
          key: strangler-cache-${{ github.ref_name }}-v1

      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache

      - name: Step -> Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Step -> Run Rubocop test
        run: bundle exec rubocop
