name: CI - Testing Cache Anything New | Action
on:
  push:

jobs:
  cache:
    name: Setup Cache | Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # It is required to execute the cache action.
      #   id: It will be use in the cache anything action.
      #   path: It always should be start with 'runner.temp'.
      - name: Step -> Generate cache
        id: cache-id
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache
          key: cache-wkhtmltopdf-v1

      # Implement the cache anything action.
      #   is_cached: Use the previous cache action id.
      #   cache: It should be the same as the cache 'path'. The default prefix is '${{ runner.temp }}/' for this reason
      #          it's not required in this field.
      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'

      - name: Step -> Use the cache
        run: |
          whereis wkhtmltopdf || true

  test:
    name: Testing | Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # It is required to execute the cache action.
      #   id: It will be use in the cache anything action.
      #   path: It always should be start with 'runner.temp'.
      - name: Step -> Generate cache
        id: cache-id
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/cache
          key: cache-wkhtmltopdf-v1

      # Implement the cache anything action.
      #   is_cached: Use the previous cache action id.
      #   cache: It should be the same as the cache 'path'. The default prefix is '${{ runner.temp }}/' for this reason
      #          it's not required in this field.
      - name: Step -> Cache anything
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'

      - name: Step -> Use the cache
        run: |
          whereis wkhtmltopdf || true

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true
      #
      # - name: Step -> Rubocop
      #   run: bundle exec rubocop
      #
      # - name: Step -> Bundler Audit
      #   run: |
      #     bundle exec bundler-audit update
      #     bundle exec bundler-audit
